/**
 * Better Auth — JSON File Database Adapter
 *
 * Moved from packages/database/adapters/json/src/better-auth-adapter.ts into the
 * bot package so it can import from 'better-auth/adapters' without requiring a
 * second better-auth installation in the json adapter package.
 *
 * The json adapter package has no better-auth dependency and should remain that way —
 * it is a zero-dependency flat-file store. This file is the only consumer of
 * better-auth's adapter factory and belongs here where better-auth is already declared.
 *
 * store.ts stays in the json adapter package because it is also consumed by the
 * standalone repo files (bot-session-commands.repo.ts, etc.) — only this bridge file moves.
 */

import { createAdapterFactory } from 'better-auth/adapters';
import type { DBAdapterDebugLogOption } from 'better-auth/adapters';
// Cross-package relative path — valid in ESM nodenext since packages/bot owns this file
// and Node resolves relative paths at the filesystem level regardless of package boundaries.
import { getDb, saveDb } from '../../../../database/adapters/json/src/store.js';

// ── Config ────────────────────────────────────────────────────────────────────

interface JsonAdapterConfig {
  debugLogs?: DBAdapterDebugLogOption;
  /** Mirror of createAdapterFactory's usePlural — set true if table names are pluralised. */
  usePlural?: boolean;
}

// ── Where-clause helpers ──────────────────────────────────────────────────────

type Operator =
  | 'eq' | 'ne'
  | 'lt' | 'lte' | 'gt' | 'gte'
  | 'in' | 'contains' | 'starts_with' | 'ends_with';

interface WhereClause {
  field: string;
  value: unknown;
  operator?: Operator;
  connector?: 'AND' | 'OR';
}

/**
 * Evaluates a better-auth where-clause array against a single in-memory record.
 * Default operator: 'eq'. Default connector: 'AND'.
 * Processes clauses left-to-right, accumulating AND/OR result sequentially.
 */
function matchesWhere(
  record: Record<string, unknown>,
  where: WhereClause[],
): boolean {
  // Empty where = match everything (e.g. findMany with no filter)
  if (!where.length) return true;

  let result = true;

  for (const clause of where) {
    const { field, value, operator = 'eq', connector = 'AND' } = clause;
    const rv = record[field];
    let match: boolean;

    switch (operator) {
      case 'eq':          match = rv === value; break;
      case 'ne':          match = rv !== value; break;
      case 'lt':          match = (rv as number) < (value as number); break;
      case 'lte':         match = (rv as number) <= (value as number); break;
      case 'gt':          match = (rv as number) > (value as number); break;
      case 'gte':         match = (rv as number) >= (value as number); break;
      case 'in':          match = Array.isArray(value) && (value as unknown[]).includes(rv); break;
      case 'contains':    match = typeof rv === 'string' && rv.includes(String(value)); break;
      case 'starts_with': match = typeof rv === 'string' && rv.startsWith(String(value)); break;
      case 'ends_with':   match = typeof rv === 'string' && rv.endsWith(String(value)); break;
      default:            match = rv === value;
    }

    if (connector === 'OR') {
      result = result || match;
    } else {
      // AND — short-circuit is intentionally skipped so every clause is evaluated
      // even after a false result, preserving correct OR chain behaviour later.
      result = result && match;
    }
  }

  return result;
}

/** Returns the table array for a given model, initialising it lazily if absent. */
function getTable(
  db: Record<string, Record<string, unknown>[]>,
  model: string,
): Record<string, unknown>[] {
  if (!db[model]) db[model] = [];
  // noUncheckedIndexedAccess guard — db[model] is guaranteed non-null from above
  return db[model] as Record<string, unknown>[];
}

// ── Adapter factory ───────────────────────────────────────────────────────────

export const jsonAdapter = (config: JsonAdapterConfig = {}) =>
  createAdapterFactory({
    config: {
      adapterId: 'cat-bot-json-adapter',
      adapterName: 'Cat-Bot JSON File Adapter',
      usePlural: config.usePlural ?? false,
      debugLogs: config.debugLogs ?? false,
      // JSON files represent objects natively — no need to stringify
      supportsJSON: true,
      // Dates stored as ISO strings in the JSON file; better-auth will coerce on read
      supportsDates: false,
      // JavaScript booleans are native JSON values
      supportsBooleans: true,
      // Use string UUIDs generated by better-auth — the JSON store has no auto-increment
      supportsNumericIds: false,
    },

    adapter: () => ({
      // ── Create ─────────────────────────────────────────────────────────────
      create: async ({ model, data }) => {
        const db = (await getDb()) as Record<string, Record<string, unknown>[]>;
        const table = getTable(db, model);
        table.push(data as Record<string, unknown>);
        await saveDb();
        return data;
      },

      // ── Find one ───────────────────────────────────────────────────────────
      findOne: async ({ model, where }) => {
        const db = (await getDb()) as Record<string, Record<string, unknown>[]>;
        const table = getTable(db, model);
        const record = table.find((r) =>
          matchesWhere(r, where as WhereClause[]),
        );
        return record ?? null;
      },

      // ── Find many ──────────────────────────────────────────────────────────
      findMany: async ({ model, where, limit, offset, sortBy }) => {
        const db = (await getDb()) as Record<string, Record<string, unknown>[]>;
        let table = [...getTable(db, model)];

        // Filter
        if (where && (where as WhereClause[]).length > 0) {
          table = table.filter((r) => matchesWhere(r, where as WhereClause[]));
        }

        // Sort — copy before sorting to avoid mutating the stored reference
        if (sortBy) {
          const { field, direction } = sortBy as { field: string; direction: 'asc' | 'desc' };
          table.sort((a, b) => {
            const av = a[field];
            const bv = b[field];
            const cmp = av === bv ? 0 : (av as string) < (bv as string) ? -1 : 1;
            return direction === 'desc' ? -cmp : cmp;
          });
        }

        // Paginate
        if (typeof offset === 'number' && offset > 0) table = table.slice(offset);
        if (typeof limit === 'number' && limit > 0) table = table.slice(0, limit);

        return table;
      },

      // ── Update (single) ────────────────────────────────────────────────────
      update: async ({ model, where, update }) => {
        const db = (await getDb()) as Record<string, Record<string, unknown>[]>;
        const table = getTable(db, model);
        const record = table.find((r) => matchesWhere(r, where as WhereClause[]));
        if (record) {
          Object.assign(record, update);
          await saveDb();
        }
        return record ?? null;
      },

      // ── Update many ────────────────────────────────────────────────────────
      updateMany: async ({ model, where, update }) => {
        const db = (await getDb()) as Record<string, Record<string, unknown>[]>;
        const table = getTable(db, model);
        let count = 0;
        for (const r of table) {
          if (matchesWhere(r, where as WhereClause[])) {
            Object.assign(r, update);
            count++;
          }
        }
        if (count > 0) await saveDb();
        return count;
      },

      // ── Delete (single) ────────────────────────────────────────────────────
      delete: async ({ model, where }) => {
        const db = (await getDb()) as Record<string, Record<string, unknown>[]>;
        const table = getTable(db, model);
        const idx = table.findIndex((r) =>
          matchesWhere(r, where as WhereClause[]),
        );
        if (idx !== -1) {
          table.splice(idx, 1);
          await saveDb();
        }
      },

      // ── Delete many ────────────────────────────────────────────────────────
      deleteMany: async ({ model, where }) => {
        const db = (await getDb()) as Record<string, Record<string, unknown>[]>;
        const table = getTable(db, model);
        const before = table.length;
        const filtered = (where as WhereClause[]).length
          ? table.filter((r) => !matchesWhere(r, where as WhereClause[]))
          : [];
        db[model] = filtered;
        const count = before - filtered.length;
        if (count > 0) await saveDb();
        return count;
      },

      // ── Count ──────────────────────────────────────────────────────────────
      count: async ({ model, where }) => {
        const db = (await getDb()) as Record<string, Record<string, unknown>[]>;
        const table = getTable(db, model);
        if (!where || !(where as WhereClause[]).length) return table.length;
        return table.filter((r) => matchesWhere(r, where as WhereClause[])).length;
      },
    }),
  });